[project]
name = "mulvis-local"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flagembedding>=1.3.4",
    "pymilvus>=2.5.8",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]
